openapi: '3.0.2'

info:
  title: Family Budget
  version: '1.0'

servers:
  - url: http://localhost:8000

tags:
  - name: Revenue
  - name: Expense

paths:
  /revenues:
    get:
      tags:
        - "Revenue"
      operationId: getAllRevenues
      responses:
        '200':
          description: "Successfully found all Revenue Entities"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/RevenueDTO"
    post:
      tags:
        - "Revenue"
      operationId: postRevenue
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RevenueDTO"
      responses:
        '201':
          description: "Successfully created Revenue Entity"
        '400':
          $ref: "#/components/responses/BadRequest"
  
  /revenues/{revenueId}:
    get:
      tags:
        - "Revenue"
      operationId: getRevenue
      parameters:
        - name: revenueId
          required: true
          in: path
          schema:
            $ref: "#/components/schemas/RevenueId"
      responses:
        '200':
          description: "Successfully found Revenue Entity"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RevenueDTO"
        '404':
          $ref: "#/components/responses/NotFound"
    put:
      tags:
        - "Revenue"
      operationId: updateRevenue
      parameters:
        - name: revenueId
          required: true
          in: path
          schema:
            $ref: "#/components/schemas/RevenueId"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RevenueDTO"
      responses:
        '200':
          description: "Successfully updated Revenue Entity"
        '400':
          $ref: "#/components/responses/BadRequest"
        '404':
          $ref: "#/components/responses/NotFound"
    delete:
      tags:
        - "Revenue"
      operationId: deleteRevenue
      parameters:
        - name: revenueId
          required: true
          in: path
          schema:
            $ref: "#/components/schemas/RevenueId"
      responses:
        '200':
          description: "Successfully removed Revenue Entity"
        '404':
          $ref: "#/components/responses/NotFound"

  /expenses:
    get:
      tags:
        - "Expense"
      operationId: getAllExpenses
      responses:
        '200':
          description: "Successfully found all Expense Entities"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ExpenseGetDTO"
    post:
      tags:
        - "Expense"
      operationId: postExpense
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ExpensePostDTO"
      responses:
        '201':
          description: "Successfully created Expense Entity"
        '400':
          $ref: "#/components/responses/BadRequest"
  
  /expenses/{expenseId}:
    get:
      tags:
        - "Expense"
      operationId: getExpense
      parameters:
        - name: expenseId
          required: true
          in: path
          schema:
            $ref: "#/components/schemas/ExpenseId"
      responses:
        '200':
          description: "Successfully found Expense Entity"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ExpenseGetDTO"
        '404':
          $ref: "#/components/responses/NotFound"
    put:
      tags:
        - "Expense"
      operationId: updateExpense
      parameters:
        - name: expenseId
          required: true
          in: path
          schema:
            $ref: "#/components/schemas/ExpenseId"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ExpensePutDTO"
      responses:
        '200':
          description: "Successfully updated Expense Entity"
        '400':
          $ref: "#/components/responses/BadRequest"
        '404':
          $ref: "#/components/responses/NotFound"
    delete:
      tags:
        - "Expense"
      operationId: deleteExpense
      parameters:
        - name: expenseId
          required: true
          in: path
          schema:
            $ref: "#/components/schemas/ExpenseId"
      responses:
        '200':
          description: "Successfully removed Expense Entity"
        '404':
          $ref: "#/components/responses/NotFound"

components:
  schemas:
    Error:
      type: object
      required:
        - code
        - message
        - trace
      properties:
        code:
          type: integer
        message:
          type: string
        trace:
          type: string
        fieldList:
          type: array
          items:
            $ref: "#/components/schemas/ErrorField"
    ErrorField:
      type: object
      required:
        - code
        - message
        - field
      properties:
        code:
          type: string
        message:
          type: string
        field:
          type: string
    
    RevenueDTO:
      type: object
      required:
        - "description"
        - "quantity"
        - "date"
      properties:
        description:
          type: string
          example: "Salary"
        quantity:
          type: number
          example: 1383.14
        date:
          type: string
          format: date
    
    ExpenseGetDTO:
      type: object
      properties:
        description:
          type: string
          example: "Gym"
        quantity:
          type: number
          example: 131.41
        date:
          type: string
          format: date
        category:
          $ref: "#/components/schemas/CategoryEnum"
    ExpensePostDTO:
      type: object
      required:
        - "description"
        - "quantity"
        - "date"
      properties:
        description:
          type: string
          example: "Gym"
        quantity:
          type: number
          example: 131.41
        date:
          type: string
          format: date
        category:
          $ref: "#/components/schemas/CategoryEnum"
    ExpensePutDTO:
      type: object
      required:
        - "description"
        - "quantity"
        - "date"
      properties:
        description:
          type: string
          example: "Gym"
        quantity:
          type: number
          example: 131.41
        date:
          type: string
          format: date

    RevenueId:
      $ref: "#/components/schemas/IntegerId"
    ExpenseId:
      $ref: "#/components/schemas/IntegerId"
    IntegerId:
      type: integer
      format: int32

    CategoryEnum:
      type: string
      enum:
        - 'FOOD'
        - 'HEALTH'
        - 'HOME'
        - 'TRANSPORT'
        - 'EDUCATION'
        - 'LEISURE'
        - 'UNFORESEEN'
        - 'OTHERS'

  responses:
    NotFound:
      description: "Could not find specific Entity"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
    BadRequest:
      description: "Could not create/update Entity"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
    Deleted:
      description: "Successfully deleted Entity"
    